owner = "SE-legacy"
repo = "formal-languages-exam-4sem"

[[issues]]
title = "Вопрос 1. Общая структура компиляторов"

[[issues]]
title = "Вопрос 2. Формальные языки"

[[issues]]
title = "Вопрос 3. Методы представления бесконечных языков"

[[issues]]
title = "Вопрос 4. Классификация грамматик языков по Хомскому"

[[issues]]
title = "Вопрос 5. Регулярные множества и регулярные выражения"

[[issues]]
title = "Вопрос 6. Конечные автоматы и регулярные множества"

[[issues]]
title = "Вопрос 7. Свойства регулярных языков. Свойства замкнутости. Разрешимые свойства"

[[issues]]
title = "Вопрос 8. Контекстно-свободные грамматики"

[[issues]]
title = "Вопрос 9. Нормальные формы КС-грамматик. Нормальная форма Хомского"

[[issues]]
title = "Вопрос 10. Автоматы с магазинной памятью"

[[issues]]
title = "Вопрос 11. Свойства КС-языков"

[[issues]]
title = "Вопрос 12. Машины Тьюринга"